=== KrichNik/Java_Web_course/src/summarytask3/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nure.ua/datsenko/SummaryTask3/entity" 
	xmlns:tns="http://nure.ua/datsenko/SummaryTask3/entity">

	<xsd:element name="Computer">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Device" 
					type="tns:Device" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Device">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string" />
			<xsd:element name="Origin" type="xsd:string" />		
			<xsd:element name="Type" type="tns:Type"/>
		</xsd:sequence>
		<xsd:attribute name="price" type="xsd:int" default="0" />	
		<xsd:attribute name="critical" type="xsd:boolean" default="false" />
	</xsd:complexType>
	
	<xsd:complexType name="Type">
		<xsd:sequence>
			<xsd:element name="EnergyConsumption" type="xsd:int" />
			<xsd:element name="Group" type="xsd:string" />
			<xsd:sequence>
				<xsd:element name="Port" type="xsd:string" maxOccurs="3"/>
			</xsd:sequence>	
		</xsd:sequence>
		<xsd:attribute name="isPeripheral" type="xsd:boolean" default="false" />	
		<xsd:attribute name="hasCooler" type="xsd:boolean" default="false" />
	</xsd:complexType>
</xsd:schema>

=== KrichNik/Java_Web_course/src/summarytask3/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<st3:Computer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:st3="http://nure.ua/datsenko/SummaryTask3/entity"
		xsi:schemaLocation="http://nure.ua/datsenko/SummaryTask3/entity input.xsd">		
		
	<Device price="1000" critical="true">	
		<Name>Matherboard</Name>
		<Origin>China</Origin>
		<Type isPeripheral = "false" hasCooler="true">
			<EnergyConsumption>10</EnergyConsumption>
			<Group>IO</Group>
			<Port>USB</Port>
			<Port>HDMI</Port>
			<Port>LPT</Port>
		</Type>
	</Device>	

	<Device price="500" critical="false">	
		<Name>Printer</Name>
		<Origin>Korea</Origin>
		<Type isPeripheral = "true" hasCooler="false">
			<EnergyConsumption>30</EnergyConsumption>
			<Group>MM</Group>
			<Port>USB</Port>
			<Port>LPT</Port>
		</Type>
	</Device>	

	<Device price="400" critical="true">	
		<Name>Hard-drive</Name>
		<Origin>USA</Origin>
		<Type isPeripheral = "false" hasCooler="false">
			<EnergyConsumption>8</EnergyConsumption>
			<Group>IO</Group>
			<Port>USB</Port>
		</Type>
	</Device>
</st3:Computer>
